//action types define const 
export const AUTHENTICATED = 'AUTHENTICATED'
export const NOT_AUTHENTICATED = 'NOT_AUTHENTICATED'
export const ADD_COINS = 'ADD_COINS'
export const FETCH_INITIAL_COINS_INFO = 'FETCH_INITIAL_COINS_INFO'